-- Correr esto una vez en el SQL editor de Supabase (Project > SQL Editor).
-- Guarda los mensajes del libro de visitas y alimenta en vivo capítulo II
-- (mensajes) y capítulo IV (visitas) de lemon.luciel.dev/regalo.

create table if not exists public.guestbook_messages (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 1 and 60),
  message text not null check (char_length(message) between 1 and 500),
  avatar_src text not null,
  hue integer not null default 200,
  created_at timestamptz not null default now()
);

alter table public.guestbook_messages enable row level security;

-- Sin moderación: cualquiera con el link puede publicar y leer.
create policy "public can read guestbook"
  on public.guestbook_messages
  for select
  to anon
  using (true);

create policy "public can insert guestbook"
  on public.guestbook_messages
  for insert
  to anon
  with check (true);
