-- Correr esto una vez en el SQL editor de Supabase (Project > SQL Editor).
-- Guarda los mensajes del libro de visitas y alimenta en vivo capítulo II
-- (mensajes) y capítulo IV (visitas) de lemon.luciel.dev/regalo.

create table if not exists public.guestbook_messages (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 1 and 60),
  message text not null check (char_length(message) between 1 and 500),
  avatar_src text not null,
  hue integer not null default 200,
  created_at timestamptz not null default now()
);

alter table public.guestbook_messages enable row level security;

-- Sin moderación: cualquiera con el link puede publicar y leer.
create policy "public can read guestbook"
  on public.guestbook_messages
  for select
  to anon
  using (true);

create policy "public can insert guestbook"
  on public.guestbook_messages
  for insert
  to anon
  with check (true);

-- Álbum "Momentos" (capítulo I): fotos/video que cualquier visitante puede
-- sumar desde la web. Antes de correr esta parte:
--   1. Storage > New bucket > nombre exacto "momentos", marcarlo "Public bucket".
--      Recomendado en la config del bucket: límite de tamaño ~20MB y mime
--      types permitidos image/*, video/mp4, video/quicktime.
--   2. Correr el SQL de abajo.

create table if not exists public.momentos_photos (
  id bigint generated by default as identity primary key,
  src text not null, -- URL pública de la imagen (o del poster si es video)
  video text, -- URL pública del video; null si la entrada es solo una foto
  caption text not null default '' check (char_length(caption) <= 120),
  created_at timestamptz not null default now()
);

alter table public.momentos_photos enable row level security;

create policy "public can read momentos"
  on public.momentos_photos
  for select
  to anon
  using (true);

create policy "public can insert momentos"
  on public.momentos_photos
  for insert
  to anon
  with check (true);

-- Permite subir archivos al bucket "momentos" desde el cliente (anon).
create policy "public can upload to momentos bucket"
  on storage.objects
  for insert
  to anon
  with check (bucket_id = 'momentos');
